DECLARE SUB MULTIKEYSTART ()
DECLARE SUB MULTIKEYSTOP ()

DECLARE SUB MULTIKEYUPDATE (T%)

DECLARE FUNCTION MULTIKEYDOWN% (T%)
DECLARE FUNCTION MULTIKEYUP% (T%)
DECLARE FUNCTION MULTIKEYPRESSED% (T%)
